services:
  - type: web
    name: gestion-tache-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    workingDir: backend
    region: oregon
